# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rrIkzAkvQB356AcGklCwIdE-3p8fHyV6
"""

a = True
a= False
b = a
print (a)

a =5
print(type(a))

a="hello"
b="world"
c = a+b
print(c)

"hello"*20

"hello"+ "1"

print("gretings from {}! have a {} day".format("ineoron","good"))

a =5
b =4
c=a+b
print("the sum of {} and {} is {}".format(c,b,a))

print("the sum of"," ",a, "and " ,b," is ",c )

a = int (input("enter value of a"))
b = int (input("enter value of b"))
c= a+b
print (" the value of {}and {} is {}".format(a,b,c))

a = int(input("enter value of a"))
print(type(a))

first_cup = "coffee"
second_cup = "tea"

print("first_cup contains {},and second_cup contains {}".format(first_cup,second_cup))
temporary_cup = 0
temporary_cup = first_cup
first_cup = second_cup
second_cup = temporary_cup
print("first_cup contains {},and second_cup contains {}".format(first_cup,second_cup))

print("hello world")

#addition operation
200+200

a = 5
b = 6
c = a+b
c

#subtartion operation 
a = 5
b = 6
c = a-b
print(c)

# comparison operators
'''

1.>
2.<
3.>=
4.<=
5.==
6.!=
'''

#logical operator

'''
1.!
2.and
3.or

'''
x = True
print(not x)


x = False
y = True 

print (x or y )

# assaigment operator

# = 
a = 5 
print (a)

# shorthand operator

'''
1. +-
2. -=
3.*=
4./=
'''

a = 398988
b = 577322
a -= b
print (a)

7**4

# if else statement 2

grade = int(input("enter your semester grade"))

if   grade >=80:
     print("You can get a laptop")
elif grade >=90:
     print("You can get a bike")
elif grade >=75:
      print("You can get a phone") 
else :
      print("study hard")

a supermarket wants to give discount to its customers following the criteria:

 total products brought                             purchase made                         discount
 1. >10                                               >8000                                 55
 2. >=7                                               >5000                                 40
 3. >=5                                               >3000                                 20
 4. >=1                                               >500                                  08

number = 20
for i in range(1,12,1):
  print(number,"x",i,"=",number*i)

i = 0
while i<25:
  i= i+2
  if (i==10):
    continue
  elif i == 14:
    break
  print(i**2)

for i in range(1,10,1):
   print(i)

n=int(input())
if n==2:
  print("prime")
else: 
  for i in range (2,n):
    if n%1==0:
      break
  print("not prime")

n=int(input())
 
 c=0
 for i in range(1,10):
   if(n%i==0):
     c=c+1
 if(c==2):
   print("prime")
 else:
   print("not prime")

for i in range (1,4):
  for j in range (1,4):
    print(j,end=" ") 
  print()

for i in range(1,5):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

a=1
for i in range(1,4):
  for j in range(1,4):
    print(a,end=" ")
    a+=1
  print()

for i in range(1,4):
  a=1
  for j in range(1,4):
    print(a,end="")
    a+=1
    print(a,end="") 
    print()

for i in range(1,4):
  a=i
  for j in range(1,4):
    print(a,end=" ")
    a+=3
  print()

import math
math.pow(2,3)

import math
math.hypot(1,2)

import math 
math.degrees(5)

import math
math.radians(3)

math.atan(0)

a=int(input())
b=int(input())
c=int(input())
greatest = 0
if a > b and a > c:
  greatest = a
elif b > a and b > c:
  greatest = b
else:
   greatest = c 
print(greatest)

a=int(input())
b=int(input())
c=int(input())
greatest=0
if a > b and a > c:
   greatest=a
elif b > a and b > c:
    greatest=b
else:      
      greatest=c
print(greatest  )

s = "hi"
a=input()
print(s+" "+a)

s="karthik"
print(s[5])

s="karthik"
print(s[:4])

s=5
print("mahesh babu",s)

n="sai"
print(n[-1])

n="hi "
print(n[-2])

my_list= [1,2,3]
print(type(my_list))
print(my_list)

lst = ['a','c','d','e','f','g','h','i','j','k','l','m','n','o','u']
for i in lst:
  if i=='a'or i=='e' or i=='i' or i=='o' or i=='u':
    print (i)

1

#min()of the a tuple
t=(5,9,2,8)
max(t)

x = set()

#show
x

def add_even(lst):
  add=0;
  for i in lst:
      add= add +i
  return add
print(add_even([1,2,4,5,6]))

def fun(lst):
  l1=[]
  for i in lst:
    if i%2 ==0:
      l1.append(i)
  add=0
  for  i in l1:
    add =add+i
  return add
print(fun([1,2,3,6,7,9]))

def is_prime(x):    
    if x==2:
       print("prime")
    else:
        for i in range(2,x+1):
            if x % i ==0:
                break
        if x==i:
            print("prime")
        else:
             print("not prime")
print(is_prime(10))

def add(x,y):
    return x+y

4+8

def sub(x,y):
    return x-y

5-9

print('hello world' )

f = open ("hello.txt" , "w")
print(f"heelo world ")
f.close()

f=open("hello.txt","r")
print(f.read())
f.close()

f=open("hello.txt","r+")
print(f.tell())
print(f.read())
print(f.tell())
f.write("hello world")
print(f.read())
print(f.tell())
f.close()

f=open("hello.txt","r")
print(f.read(2))
f.close()

f=open("hello.txt","r")
print(f.read(2))
print(f.seek(5))
f.close()

f=open("hello.txt","r")#open a file
print("file number:",f.fileno())

f.close()

def student_info_function():
  
  dic["reg_no"] =input("reg_no:")
  '''
  dic["roll_no"] = input("roll number")
  dic["student_name"]=input("name:")
  dic["class"]=input("class:")
  dic["section"]=input("section:")
  dic[guardian_name]=input("guardian name:")
  return (dic):

def academics_info_function():
    dic = {}
    no_of_sub_ = int(input("enter number of subjects:"))
    for i in the range(no_of_subject) 
        sub_name=float(input("subject marks")):
        sub_name = input("")

def in_info_function():
    dic ={}
    dic["discipline"] = float(input("disciplane:"))
    dic["honest"] = float(input("honesst:"))

def academics_percentage(academics_info):
   percentage =0
   add =0
   for i in academics_info.values():
           add =add +i
   percentage = add/no .of(academics_info)
   return (percentage)

def main():
  academains__info,cca_info,im_info = student input()
  ac_grade

def calculate_percentage():
  academics _info, cca_info, in_info= student_input()
  aca_per = calculate_percentage(academics_info)
  cca_per = calc_percentage(cca_info)
  in_per = calc_percentage(in_info)
  returns aca_per,cca_per, in_per

def calcute_net_grade(net_per):
  net_grade =''
  if net_ per>90:
    net grade

def remarks(net_grade)
 remarks ='
 if net_grade =='A'
 remaks = 'out standing work!! keep it up'
 elif net_grade =='B'
 remarks = "very good !! do work hard"
 elif net grade== 'C'
 remarks ="good performance"
 elif net grade=='D'
 remarks ="keep it up"
 elif net grade=="E"
 remarks ="better luck next time "
 elif net grade=="F"
 remarks ="fail"

j=int(input("enter number"))
if j==3:
  print("prime")
else:
 for i in range(3,j):
  if j%1 ==0:
    break
print("not prime")

print("SALARY PROGRAM")
name= str(input("Enter name of employee:"))
basic=float(input("Enter Basic Salary :"))
da=float(basic*0.25)
hra=float(basic*0.15)
pf=float((basic+da)*0.12)
ta=float(basic*0.075)
netpay=float(basic+da+hra+ta)
grosspay=float(netpay-pf)

print("\n\n")
print("S A L A R Y D E T A I L E D B R E A K U P ")
print("==============================================")
print(" NAME OF EMPLOYEE : ",name)
print(" BASIC SALARY : ",basic)
print(" DEARNESS ALLOW. : ",da)
print(" HOUSE RENT ALLOW.: ",hra)
print(" TRAVEL ALLOW. : ",ta)
print("==============================================")
print(" NET SALARY PAY : ",netpay)
print(" PROVIDENT FUND : ",pf)
print("==============================================")
print(" GROSS PAYMENT : ",grosspay)
print("==============================================")

